### ISSUE TITLE
thirdparty submodule opengv ref commit does not exist

### ISSUE THREAD

**Issue by xclord** [Unsigned-Long/iKalibr#1]
commit id: 7d02083da8c60d8783683d33518938aa8c56a9d6

**Comment by Unsigned-Long** [comment]
Sorry for our carelessness. When we submitted the code, we also submitted the submodule `opengv` library, which caused the `opengv` index maintained by this repository to be inconsistent with the remote `opengv` index.

Now we have recreated the `opengv` library index. You can follow the steps in the [tutorial](https://github.com/Unsigned-Long/iKalibr/blob/master/docs/details/build_ikalibr.md) again to configure the environment and compile `iKalibr` :smiley:  .
