### ISSUE TITLE
求相关文献推荐

### ISSUE THREAD

**Issue by billionon** [Unsigned-Long/iKalibr#11]
大佬你好，目前想对连续时间slam方面做一些研究，奈何对涉及到李群的姿态样条的表示还有解析导数的内容很难理解。目前也看了一些开源的代码(浙大和basalt的)，里面解析导数的部分也很抽象。想请教下大佬是怎么学习这方面的内容的，以及有无比较好的文献能够帮助理解前面提到的难点

**Comment by Unsigned-Long** [comment]
关于李群李代数的知识，我感觉可以看一下这一篇文章：A micro Lie theory for state estimation in robotics。可能一开始看比较难，但是多看几遍其实也是可以理解的。另外，前期学习不要追求把啥都弄懂，有个大概了解就行了。先用着，后面回过头看就简单了。

**Comment by billionon** [comment]
好的好的，感谢大佬
