### ISSUE TITLE
about env configure

### ISSUE THREAD

**Issue by QiuYue-bit** [Unsigned-Long/iKalibr#12]
您好，我在配置环境的时候发现一些冲突的地方，我的系统是Ubutnu20.04,ROS1 NOETIC
默认的Eigen安装的是3.3.7，glog版本0.6.0
在配置环境的时候发现Glomap-1.0.0 和  Sophus 都明确要求了 Eigen的版本为3.4.0，而ROS默认的Eigen也为3.3.7，在我修改GLOMAP和Sophus的CmakeLists，使用3.3.7后，编译出现了Eigen相关的错误，请问您有遇到这个问题吗？
或者您用的各个库的版本是什么呢？
![image](https://github.com/user-attachments/assets/4027af8d-753f-4492-92f7-d2f4313a9b33)

**Comment by QiuYue-bit** [comment]
在glomap里面的issue有一个类似的报错：https://github.com/colmap/glomap/issues/66
Solve method: Must using eigen 3.4.

**Comment by Unsigned-Long** [comment]
我这边用的都是eigen 3.4.0的版本，所有的库编译都能通过，你可以尝试一下。
