### ISSUE TITLE
Couldn't find current GLX or EGL context

### ISSUE THREAD

**Issue by Raidenzheng** [Unsigned-Long/iKalibr#16]
![ikalibr](https://github.com/user-attachments/assets/dd9bbcb8-8301-42f5-85ba-e206c6b3c9c7)
运行时提示ikalibr_prog: ../src/dispatch_common.c:863：epoxy_get_proc_address: 假设 ‘0 && "Couldn't find current GLX or EGL context.\n"’ 失败。
请问是什么原因？我检查了OpenGL和epoxy。都安装好了。
如果这个只是一个显示功能，能否关掉。仅输出外参结果？

**Comment by Unsigned-Long** [comment]
你`pangolin`安装的是那个版本？这个问题我们好像之前也遇到过，装最新版本的`pangolin`就会出现这个问题。你使用`v0.8`版本的`pangolin`看看：
```sh
# pangolin (v0.8)
git clone --branch v0.8 --single-branch --recursive https://github.com/stevenlovegrove/Pangolin.git
# then cmake, make, and install
```
我们已经提供了一个在ubuntu 20.04下测试过的环境配置，请参考[build_ikalibr.md](https://github.com/Unsigned-Long/iKalibr/blob/master/docs/details/build_ikalibr.md)文末，每个库的版本都有详细给出。
