### ISSUE TITLE
name suggestion

### ISSUE THREAD

**Issue by changh95** [Unsigned-Long/iKalibr#2]
(Not strictly related to the code)

If your calibration framework is inspired by Kalibr, and supports calibrating all kinds of sensor configurations (i.e. X-configuration)...

Why not call it xKalibr, like the sword [excalibur](https://en.wikipedia.org/wiki/Excalibur)? Just a suggestion! :smile:

**Comment by Unsigned-Long** [comment]
Thanks for your issue :smiley:. In fact, the reason why `iKalibr` is called `iKalibr` has been explained clearly [here](https://github.com/Unsigned-Long/iKalibr/blob/master/docs/details/why_ikalibr.md) (including the origin of the first letter `i` in `iKalibr` and the relationship between `iKalibr` and `Kalibr`). In addition, please note that the only similarity between `iKalibr` and `Kalibr` is that they use the continuous-time estimation method (the underlying estimation method), and almost everything else is different.

**Comment by changh95** [comment]
Fully understood!
Thank you for your reply :)

Closing the issue as solved!
