### ISSUE TITLE
关于论文中传感器平台数据传输设计

### ISSUE THREAD

**Issue by cchester25** [Unsigned-Long/iKalibr#5]
您好，在论文中，数据采集的平台有两款激光雷达，两个相机，请问这些传感器的数据传输用的是千兆交换机还是万兆交换机呢？

**Comment by Unsigned-Long** [comment]
我们用的好像是这一款[交换机](https://item.m.jd.com/product/100035044210.html?gx=RnAomTM2bzbcw8tHqtZwCIK9Wp4LkIk&gxd=RnAowmZdOmGIzZodpoMmWzx65T1-Iok&ad_od=share&utm_source=androidapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=QQfriends)，10口千兆|8口poe:57W，应该是千兆的交换机。

**Comment by cchester25** [comment]
> 我们用的好像是这一款[交换机](https://item.m.jd.com/product/100035044210.html?gx=RnAomTM2bzbcw8tHqtZwCIK9Wp4LkIk&gxd=RnAowmZdOmGIzZodpoMmWzx65T1-Iok&ad_od=share&utm_source=androidapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=QQfriends)，10口千兆|8口poe:57W，应该是千兆的交换机。

好的，谢谢您的解答。
