### ISSUE TITLE
关于环境配置

### ISSUE THREAD

**Issue by billionon** [Unsigned-Long/iKalibr#7]
大佬看看这是什么问题？目前就是频繁出现boost和pcl的报错，但是这两个库都是ubuntu20.04默认的版本(boost:1.71.0，pcl:1.13.0)

![Snipaste_2024-08-23_21-11-44](https://github.com/user-attachments/assets/1677c23b-7da8-4ee2-a046-cd6235b2acb0)

**Comment by Unsigned-Long** [comment]
`Ubuntu 20.04`的默认`pcl`版本是1.10，不是1.13. 使用`sudo apt-get install libpcl` 再tab tab补全，可以查看。

**Comment by billionon** [comment]
啊是的，**pcl**版本问题，重装一下就编译过了
